# SITE CONFIGURATION
baseurl: ""
url: "https://uk-oyss.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: UK Outstanding Young Scholars Society                                    # site's title
description: "A website about UK Outstanding Young Scholars Society "      # used by search engines
avatar: assets/img/header/dunhui.jpg                        # 左上角logo
favicon: assets/favicon.ico                             # tab小图标

# Header and footer text
header_text: 英国杰出青年人才协会  # Change Blog header text
header_feature_image: assets/img/header/royalacademy1.jpg #背景图
header_feature_image_responsive: true
footer_text: >
  欢迎加入通过 <a href="https://docs.google.com/forms/d/e/1FAIpQLSfU5ZGL6rfY0ZnVkw6RF8STIjcWk7G9sfniXWzuZufvlethjg/viewform?usp=sf_link">Form</a> or <a href="Mailto:oyssit2023@gmail.com">Email us</a>

# Blog
excerpt: truncate                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
